# Deep Past Initiative: Data Preprocessing

This notebook covers all data preprocessing steps for the Akkadian → English machine translation pipeline:
1. Setup & imports
2. Load competition and external datasets
3. Normalize transliterations and translations
4. Cross-dataset deduplication
5. Genre prefix conditioning
6. Stage dataset assembly
7. Glossary construction

## 1. Setup & Imports

In [13]:
# pip install -r requirements.txt

In [14]:
import os
import re
import json
import random
import unicodedata

import numpy as np
import pandas as pd

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
os.environ['PYTHONHASHSEED'] = str(SEED)

# Ensure output directories exist
os.makedirs('data', exist_ok=True)
os.makedirs('data/akkademia', exist_ok=True)
os.makedirs('models/stage1_final', exist_ok=True)
os.makedirs('models/stage2_final', exist_ok=True)
os.makedirs('models/stage3_final', exist_ok=True)
os.makedirs('outputs', exist_ok=True)

print('Setup complete.')

Setup complete.

## 2. Load Datasets

### 2a. Competition Datasets

In [15]:
train_df              = pd.read_csv('data/competition/train.csv')
test_df               = pd.read_csv('data/competition/test.csv')
sample_submission_df  = pd.read_csv('data/competition/sample_submission.csv')
sentences_oare_df     = pd.read_csv('data/competition/Sentences_Oare_FirstWord_LinNum.csv')
published_texts_df    = pd.read_csv('data/competition/published_texts.csv')
lexicon_df            = pd.read_csv('data/competition/OA_Lexicon_eBL.csv')
dictionary_df         = pd.read_csv('data/competition/eBL_Dictionary.csv')

print('Competition datasets loaded.')
print(f'  train:             {train_df.shape}')
print(f'  test:              {test_df.shape}')
print(f'  sample_submission: {sample_submission_df.shape}')
print(f'  sentences_oare:    {sentences_oare_df.shape}')
print(f'  published_texts:   {published_texts_df.shape}')
print(f'  lexicon:           {lexicon_df.shape}')
print(f'  dictionary:        {dictionary_df.shape}')
train_df.head(2)

Competition datasets loaded.
  train:             (1561, 3)
  test:              (4, 5)
  sample_submission: (4, 2)
  sentences_oare:    (9782, 12)
  published_texts:   (7953, 19)
  lexicon:           (39332, 9)
  dictionary:        (19215, 3)

,oare_id,transliteration,translation
0,004a7dbd-57ce-46f8-9691-409be61c676e,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-{d}IM KIŠI...,"Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ..."
1,0064939c-59b9-4448-a63d-34612af0a1b5,1 TÚG ša qá-tim i-tur₄-DINGIR il₅-qé,Itūr-ilī has received one textile of ordinary ...

### 2b. Akkademia Dataset

In [16]:
def load_akkademia_dataset():
    """Load Akkademia NMT_input files and return aligned DataFrames per split."""
    akkademia_data = {}
    for split in ['train', 'valid', 'test']:
        with open(f'data/akkademia/{split}.ak', 'r', encoding='utf-8') as f:
            akkadian_lines = [line.strip() for line in f]
        with open(f'data/akkademia/{split}.en', 'r', encoding='utf-8') as f:
            english_lines = [line.strip() for line in f]
        akkademia_data[split] = pd.DataFrame({
            'transliteration': akkadian_lines,
            'translation': english_lines
        })
    print('Akkademia dataset loaded.')
    for split, df in akkademia_data.items():
        print(f'  {split}: {len(df)} pairs')
    return akkademia_data

akkademia_data = load_akkademia_dataset()
akkademia_data['train'].head(2)

Akkademia dataset loaded.
  train: 50478 pairs
  valid: 2812 pairs
  test: 2870 pairs

,transliteration,translation
0,𒉭𒁄𒌀𒆠𒋗𒄣𒊒𒈾𒉘𒀭...𒀭𒊺𒊒𒀀𒀊𒁀...𒉿𒄘𒀭𒊩𒌆𒃞𒈾𒃻𒀀𒈾𒁁𒂁𒆳𒆳...𒀭𒋾𒀠𒋃......,"Precious scion of Baltil (Aššur), beloved of t..."
1,𒄣𒊏𒁺...𒌑𒊕𒉌𒋙𒊺𒁍𒍑𒋗...𒀸𒄑𒆪𒌑𒌑𒆥𒌅...𒈬𒌓𒊑𒆪...,warrior ... who made ... bow down at his feet ...

### 2c. ORACC Kaggle Dataset

In [17]:
oracc_df = pd.read_csv('data/oracc_kaggle/train.csv')
print(f'ORACC dataset loaded. Shape: {oracc_df.shape}')
print('Columns:', oracc_df.columns.tolist())

# Identify genre priority (used later for sample weighting)
GENRE_PRIORITY = {
    'HIGH':   ['letter', 'administrative', 'memo', 'note', 'decree', 'report'],
    'MEDIUM': ['legal', 'contract', 'list'],
    'LOW':    ['royal inscription', 'votive inscription', 'building inscription', 'annals'],
}
oracc_df.head(2)

ORACC dataset loaded. Shape: (2117, 3)
Columns: ['id', 'akkadian', 'english']

,id,akkadian,english
0,P236874,a - mat LUGAL a - na m d + EN — DÙ DI - mu a ....,The king's word to Bel-ibni : I am well ; you ...
1,P236876,[ x x ] ⸢ x ⸣ É ⸢ x ⸣ + [ x x x x x x x x ] [ ...,[ No ] w then my forces have co [ me and ] ass...

## 3. Text Normalization

In [18]:
# Unicode subscript digits → ASCII
_SUBSCRIPT_MAP = str.maketrans('₀₁₂₃₄₅₆₇₈₉', '0123456789')

def normalize_transliteration(text):
    """Normalize Akkadian transliteration text.

    Steps:
      - Unicode NFC normalization
      - Subscript digit mapping (₁ → 1, etc.)
      - Replace damage/lacuna markers [...] with <gap>
      - Strip scribal correction markers (!, ?, #)
      - Collapse whitespace
    """
    if pd.isna(text) or text == '':
        return text
    text = unicodedata.normalize('NFC', text)
    text = text.translate(_SUBSCRIPT_MAP)
    text = re.sub(r'\[.*?\]', '<gap>', text)
    text = re.sub(r'[!?#]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def normalize_translation(text):
    """Normalize English translation text.

    Steps:
      - Normalize fancy quotation marks to ASCII
      - Normalize whitespace
      - Strip leading/trailing editorial bracket marks
    """
    if pd.isna(text) or text == '':
        return text
    text = re.sub(r'[“”‟\u02ee\uff02]', '"', text)
    text = re.sub(r"[\u2018\u2019\u201b\u02bc\u055a]", "'", text)
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r'^[\[\]()]+|[\[\]()]+$', '', text)
    return text


# --- Quick sanity checks ---
assert normalize_transliteration('a₁-šur [broken] text!') == 'a1-šur <gap> text'
assert normalize_translation('\u201cHello\u201d') == '"Hello"'
print('Normalization functions defined and verified.')

Normalization functions defined and verified.

### 3a. Apply Normalization to All Datasets

In [19]:
# Competition train
train_df['transliteration_normalized'] = train_df['transliteration'].apply(normalize_transliteration)
train_df['translation_normalized']     = train_df['translation'].apply(normalize_translation)

# Akkademia splits
for split in ['train', 'valid', 'test']:
    akkademia_data[split]['transliteration_normalized'] = (
        akkademia_data[split]['transliteration'].apply(normalize_transliteration)
    )
    akkademia_data[split]['translation_normalized'] = (
        akkademia_data[split]['translation'].apply(normalize_translation)
    )

# ORACC — columns are 'akkadian' and 'english'
oracc_df['transliteration_normalized'] = oracc_df['akkadian'].apply(normalize_transliteration)
oracc_df['translation_normalized']     = oracc_df['english'].apply(normalize_translation)

print('Normalization applied to all datasets.')
print('Competition train sample:')
train_df[['transliteration', 'transliteration_normalized']].head(2)

Normalization applied to all datasets.
Competition train sample:

,transliteration,transliteration_normalized
0,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-{d}IM KIŠI...,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-{d}IM KIŠI...
1,1 TÚG ša qá-tim i-tur₄-DINGIR il₅-qé,1 TÚG ša qá-tim i-tur4-DINGIR il5-qé

## 4. Cross-Dataset Deduplication

In [20]:
# Build set of all normalized competition transliterations to exclude from external data
competition_translit_set = set(train_df['transliteration_normalized'].dropna())
print(f'Competition train unique transliterations: {len(competition_translit_set)}')

# --- Akkademia: remove rows that appear in competition train ---
akkademia_deduped = {}
for split in ['train', 'valid', 'test']:
    df = akkademia_data[split]
    before = len(df)
    df = df[~df['transliteration_normalized'].isin(competition_translit_set)].copy()
    df = df.drop_duplicates(subset=['transliteration_normalized'], keep='first')
    after = len(df)
    akkademia_deduped[split] = df
    print(f'  Akkademia {split}: {before} → {after} rows')

# --- ORACC: remove competition overlaps and internal duplicates ---
before = len(oracc_df)
oracc_deduped = oracc_df[
    ~oracc_df['transliteration_normalized'].isin(competition_translit_set)
].drop_duplicates(subset=['transliteration_normalized'], keep='first').copy()
print(f'  ORACC: {before} → {len(oracc_deduped)} rows')

# --- Sentences_Oare: exclude tablets that appear in competition train ---
before = len(sentences_oare_df)
sentences_oare_filtered = (
    sentences_oare_df[~sentences_oare_df['text_uuid'].isin(train_df['oare_id'])]
    .dropna(subset=['translation'])
    .copy()
)
print(f'  Sentences_Oare: {before} → {len(sentences_oare_filtered)} rows (nulls removed)')

Competition train unique transliterations: 1559
  Akkademia train: 50478 → 44511 rows
  Akkademia valid: 2812 → 2712 rows
  Akkademia test: 2870 → 2762 rows
  ORACC: 2117 → 2111 rows
  Sentences_Oare: 9782 → 8565 rows (nulls removed)

## 5. Genre Prefix Conditioning

In [21]:
GENRE_PREFIX_MAP = {
    'letter':         '[LETTER]',
    'debt note':      '[DEBT_NOTE]',
    'loan':           '[DEBT_NOTE]',
    'contract':       '[CONTRACT]',
    'administrative': '[ADMIN]',
    'admin':          '[ADMIN]',
}

def map_genre_to_prefix(genre_label):
    """Map a genre label string to its special prefix token."""
    if pd.isna(genre_label):
        return '[UNKNOWN]'
    g = genre_label.lower().strip()
    for key, prefix in GENRE_PREFIX_MAP.items():
        if key in g:
            return prefix
    return '[UNKNOWN]'


# Merge genre labels from published_texts into competition train
train_with_genre = train_df.merge(
    published_texts_df[['oare_id', 'genre_label']],
    on='oare_id',
    how='left'
)

train_with_genre['genre_prefix'] = train_with_genre['genre_label'].apply(map_genre_to_prefix)
train_with_genre['transliteration_prefixed'] = (
    train_with_genre['genre_prefix'] + ' ' + train_with_genre['transliteration_normalized']
)

print('Genre prefix conditioning applied.')
print('Genre distribution:')
print(train_with_genre['genre_prefix'].value_counts())
train_with_genre[['transliteration_normalized', 'genre_prefix', 'transliteration_prefixed']].head(3)

Genre prefix conditioning applied.
Genre distribution:
genre_prefix
[UNKNOWN]      1392
[LETTER]        150
[ADMIN]          10
[DEBT_NOTE]       5
[CONTRACT]        4
Name: count, dtype: int64

,transliteration_normalized,genre_prefix,transliteration_prefixed
0,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-{d}IM KIŠI...,[DEBT_NOTE],[DEBT_NOTE] KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-l...
1,1 TÚG ša qá-tim i-tur4-DINGIR il5-qé,[UNKNOWN],[UNKNOWN] 1 TÚG ša qá-tim i-tur4-DINGIR il5-qé
2,TÚG u-la i-dí-na-ku-um i-tù-ra-ma 9 GÍN KÙ.BABBAR,[UNKNOWN],[UNKNOWN] TÚG u-la i-dí-na-ku-um i-tù-ra-ma 9 ...

## 6. Stage Dataset Assembly

In [22]:
# ── Stage 1: Akkademia (train + valid) + ORACC ──────────────────────────────
akkademia_stage1 = pd.concat([
    akkademia_deduped['train'],
    akkademia_deduped['valid'],
])

stage1_data = pd.concat([
    akkademia_stage1[['transliteration_normalized', 'translation_normalized']],
    oracc_deduped[['transliteration_normalized', 'translation_normalized']],
], ignore_index=True).rename(columns={
    'transliteration_normalized': 'transliteration',
    'translation_normalized':     'translation',
})
stage1_data.dropna(subset=['transliteration', 'translation'], inplace=True)
print(f'Stage 1 dataset: {len(stage1_data)} rows')

# ── Stage 2: Sentences_Oare rows not in competition train ───────────────────
stage2_data = sentences_oare_filtered[
    ['text_uuid', 'translation', 'first_word_spelling', 'line_number', 'side']
].copy()
print(f'Stage 2 dataset: {len(stage2_data)} rows')

# ── Stage 3: Competition train, 90/10 doc-order split ───────────────────────
stage3_full = train_with_genre[[
    'transliteration_prefixed', 'translation_normalized'
]].rename(columns={
    'transliteration_prefixed': 'transliteration',
    'translation_normalized':   'translation',
})

split_idx    = int(len(stage3_full) * 0.9)
stage3_train = stage3_full.iloc[:split_idx].copy()
stage3_val   = stage3_full.iloc[split_idx:].copy()
print(f'Stage 3 train: {len(stage3_train)} rows  |  val: {len(stage3_val)} rows')

# ── Save to disk ─────────────────────────────────────────────────────────────
stage1_data.to_csv('data/stage1_train.csv',  index=False)
stage2_data.to_csv('data/stage2_train.csv',  index=False)
stage3_train.to_csv('data/stage3_train.csv', index=False)
stage3_val.to_csv('data/stage3_val.csv',     index=False)

print('Stage datasets saved to data/.')

Stage 1 dataset: 49334 rows
Stage 2 dataset: 8565 rows
Stage 3 train: 1404 rows  |  val: 157 rows
Stage datasets saved to data/.

## 7. Glossary Construction

In [23]:
# Extract personal names (PN), geographic names (GN), and month names (MN)
# from OA_Lexicon_eBL.csv to build a proper-name glossary.

names_df = lexicon_df[lexicon_df['type'].isin(['PN', 'GN', 'MN'])].copy()
glossary_dict = dict(zip(names_df['form'], names_df['norm']))

print(f'Glossary entries: {len(glossary_dict)}')
print('Sample entries:', dict(list(glossary_dict.items())[:5]))

with open('data/glossary.json', 'w', encoding='utf-8') as f:
    json.dump(glossary_dict, f, ensure_ascii=False, indent=2)

print('Glossary saved to data/glossary.json.')

Glossary entries: 13438
Sample entries: {'a-ba-a-a': 'Abā', 'a-ba-a': 'Abā', 'a-ba': 'Abā', 'ab-ba': 'Abā', 'a-ba-a-a-ma': 'Abāma'}
Glossary saved to data/glossary.json.

In [ ]:
# --- Preprocessing report: what was removed and before/after counts ---
# Counts before preprocessing / deduplication
before = {
    'Competition train': len(train_df),
    'Competition test':  len(test_df),
    'Akkademia train (raw)': len(akkademia_data['train']),
    'Akkademia valid (raw)': len(akkademia_data['valid']),
    'Akkademia test (raw)': len(akkademia_data['test']),
    'ORACC (raw)': len(oracc_df),
    'Sentences_Oare (raw)': len(sentences_oare_df),
}

# Counts after normalization / deduplication / filtering
after = {
    'Akkademia train (deduped)': len(akkademia_deduped['train']),
    'Akkademia valid (deduped)': len(akkademia_deduped['valid']),
    'Akkademia test (deduped)': len(akkademia_deduped['test']),
    'ORACC (deduped)': len(oracc_deduped),
    'Sentences_Oare (filtered)': len(sentences_oare_filtered),
    'Stage 1 train rows': len(stage1_data),
    'Stage 2 train rows': len(stage2_data),
    'Stage 3 train rows': len(stage3_train),
    'Stage 3 val rows': len(stage3_val),
    'Glossary entries': len(glossary_dict),
}

# Rows removed (before - after) with simple reasons
removed = {
    'Akkademia train removed (overlap/dupes)': before['Akkademia train (raw)'] - after['Akkademia train (deduped)'],
    'Akkademia valid removed (overlap/dupes)': before['Akkademia valid (raw)'] - after['Akkademia valid (deduped)'],
    'Akkademia test removed (overlap/dupes)': before['Akkademia test (raw)'] - after['Akkademia test (deduped)'],
    'ORACC removed (overlap/dupes)': before['ORACC (raw)'] - after['ORACC (deduped)'],
    'Sentences_Oare removed (nulls/overlap)': before['Sentences_Oare (raw)'] - after['Sentences_Oare (filtered)'],
    'Stage1 rows removed (missing pairs)': (len(pd.concat([akkademia_stage1[['transliteration_normalized','translation_normalized']], oracc_deduped[['transliteration_normalized','translation_normalized']]])) - len(stage1_data)),
}

import textwrap

print('=' * 80)
print('PREPROCESSING REPORT: BEFORE / AFTER / REMOVED COUNTS')
print('=' * 80)
print('\nBEFORE (loaded datasets):')
print(pd.Series(before).to_string())
print('\nAFTER (post-normalize/dedup/filter):')
print(pd.Series(after).to_string())
print('\nREMOVED (counts and primary causes):')
print(pd.Series(removed).to_string())

# Examples of normalization changes in tabular format
def get_normalization_samples(df, orig_col, norm_col, n=8):
    """Extract samples where normalization changed the text, return as DataFrame."""
    dfc = df.dropna(subset=[orig_col, norm_col]).copy()
    changed = dfc[dfc[orig_col].astype(str) != dfc[norm_col].astype(str)]
    if len(changed) == 0:
        return None
    samples = changed[[orig_col, norm_col]].drop_duplicates().head(n).copy()
    samples.columns = ['Original', 'Normalized']
    samples.index = range(1, len(samples) + 1)
    return samples

print('\n' + '=' * 80)
print('NORMALIZATION EXAMPLES (Original → Normalized)')
print('=' * 80)

# Competition train transliterations
print('\n📜 Competition Train - Transliterations')
comp_translit_samples = get_normalization_samples(train_df, 'transliteration', 'transliteration_normalized', n=8)
if comp_translit_samples is not None:
    display(comp_translit_samples)
else:
    print('  No changes detected.')

# Competition train translations
print('\n📜 Competition Train - Translations')
comp_trans_samples = get_normalization_samples(train_df, 'translation', 'translation_normalized', n=8)
if comp_trans_samples is not None:
    display(comp_trans_samples)
else:
    print('  No changes detected.')

# Akkademia transliterations
print('\n📚 Akkademia Dataset - Transliterations')
akk_translit_samples = get_normalization_samples(akkademia_data['train'], 'transliteration', 'transliteration_normalized', n=8)
if akk_translit_samples is not None:
    display(akk_translit_samples)
else:
    print('  No changes detected.')

# Akkademia translations
print('\n📚 Akkademia Dataset - Translations')
akk_trans_samples = get_normalization_samples(akkademia_data['train'], 'translation', 'translation_normalized', n=8)
if akk_trans_samples is not None:
    display(akk_trans_samples)
else:
    print('  No changes detected.')

# ORACC transliterations
print('\n🏛️ ORACC Dataset - Transliterations')
oracc_translit_samples = get_normalization_samples(oracc_df, 'akkadian', 'transliteration_normalized', n=8)
if oracc_translit_samples is not None:
    display(oracc_translit_samples)
else:
    print('  No changes detected.')

# ORACC translations
print('\n🏛️ ORACC Dataset - Translations')
oracc_trans_samples = get_normalization_samples(oracc_df, 'english', 'translation_normalized', n=8)
if oracc_trans_samples is not None:
    display(oracc_trans_samples)
else:
    print('  No changes detected.')

# Summary of cleaning actions in tabular format
print('\n' + '=' * 80)
print('CLEANING ACTIONS APPLIED (Scribbles & Noise Removed)')
print('=' * 80)

cleaning_df = pd.DataFrame({
    'Category': [
        'Unicode', 'Unicode', 'Damage Markers', 'Scribal Markers',
        'Whitespace', 'Quotation Marks', 'Editorial Marks',
        'Data Quality', 'Data Quality', 'Data Quality'
    ],
    'Action': [
        'Unicode NFC normalization',
        'Subscript digits → ASCII',
        'Bracketed lacunae → <gap>',
        'Remove correction markers',
        'Collapse & trim whitespace',
        'Normalize fancy quotes → ASCII',
        'Strip editorial brackets',
        'Drop rows missing pairs',
        'Remove duplicate transliterations',
        'Filter cross-dataset overlaps'
    ],
    'Example': [
        'ś → ś (composed form)',
        '₁ → 1, ₂ → 2',
        '[broken] → <gap>',
        'text! → text, word? → word',
        '  multiple   spaces  → single space',
        '"curly" → "straight"',
        '[translation] → translation',
        'Rows with null translation removed',
        'Keep first occurrence only',
        'Remove Akkademia/ORACC rows in competition train'
    ]
})

cleaning_df.index = range(1, len(cleaning_df) + 1)
display(cleaning_df)

print('\n✅ All preprocessing complete. Clean datasets saved to data/ directory.')

--- Preprocessing: before / after / removed counts ---
Before (loaded datasets):
Competition train         1561
Competition test             4
Akkademia train (raw)    50478
Akkademia valid (raw)     2812
Akkademia test (raw)      2870
ORACC (raw)               2117
Sentences_Oare (raw)      9782
After (post-normalize/dedup/filter):
Akkademia train (deduped)    44511
Akkademia valid (deduped)     2712
Akkademia test (deduped)      2762
ORACC (deduped)               2111
Sentences_Oare (filtered)     8565
Stage 1 train rows           49334
Stage 2 train rows            8565
Stage 3 train rows            1404
Stage 3 val rows               157
Glossary entries             13438
Removed (counts and primary causes):
Akkademia train removed (overlap/dupes)    5967
Akkademia valid removed (overlap/dupes)     100
Akkademia test removed (overlap/dupes)      108
ORACC removed (overlap/dupes)                 6
Sentences_Oare removed (nulls/overlap)     1217
Stage1 rows removed (missing pairs)           0
Examples of Competition transliteration normalizations (original → normalized):
 - KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-{d}IM KIŠIB šu-{d}EN.LÍL DUMU ma-nu-ki-a-šur KIŠIB MAN-a-šur DUMU a-ta-a 0.3333 ma-na 2 GÍN KÙ.BABBAR SIG₅ i-ṣé-er PUZUR₄-a-šur DUMU a-ta-a a-lá-ḫu-um i-šu iš-tù ḫa-muš-tim ša ì-lí-dan ITU.KAM ša ke-na-tim li-mu-um e-na-sú-in a-na ITU 14 ḫa-am-ša-tim i-ša-qal šu-ma lá iš-qú-ul 1.5 GÍN.TA a-na 1 ma-na-im i-na ITU.1.KAM ṣí-ib-tám ú-ṣa-áb → KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-{d}IM KIŠIB šu-{d}EN.LÍL DUMU ma-nu-ki-a-šur KIŠIB MAN-a-šur DUMU a-ta-a 0.3333 ma-na 2 GÍN KÙ.BABBAR SIG5 i-ṣé-er PUZUR4-a-šur DUMU a-ta-a a-lá-ḫu-um i-šu iš-tù ḫa-muš-tim ša ì-lí-dan ITU.KAM ša ke-na-tim li-mu-um e-na-sú-in a-na ITU 14 ḫa-am-ša-tim i-ša-qal šu-ma lá iš-qú-ul 1.5 GÍN.TA a-na 1 ma-na-im i-na ITU.1.KAM ṣí-ib-tám ú-ṣa-áb
 - 1 TÚG ša qá-tim i-tur₄-DINGIR il₅-qé → 1 TÚG ša qá-tim i-tur4-DINGIR il5-qé
 - KIŠIB šu-{d}EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-lu-lu DUMU ú-ku i-nu-mì i-dí-a-bu-um a-wa-sú iq-bi-ú 10 ma-na KÙ.BABBAR a-na ša-lim-a-šùr i-dí-in um-ma šu-ut-ma i-ṣí-ba-at KÙ-pì-a li-il₅-qé → KIŠIB šu-{d}EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-lu-lu DUMU ú-ku i-nu-mì i-dí-a-bu-um a-wa-sú iq-bi-ú 10 ma-na KÙ.BABBAR a-na ša-lim-a-šùr i-dí-in um-ma šu-ut-ma i-ṣí-ba-at KÙ-pì-a li-il5-qé
 - um-ma šu-ku-tum-ma a-na IŠTAR-lá-ma-sí ù ni-ta-aḫ-šu-šar qí-bi₄-ma mì-šu ša ta-áš-pu-ra-ni-ni um-ma a-tí-na-ma É-tum a-na lá be-tim i-tù-ar a-pu-tum a-na en-um-a-šùr i-<gap>-ni-ma e ší-na ga <gap> ša lá ta-ḫa-dì-ri a-na IŠTAR-lá-ma-sí qí-bi₄-ma šu-ma a-ḫa-tí a-ta li-ba-am dì-ni-ší-im lá ta-ḫa-da-ar a-na ni-ta-aḫ-šu-šar qí-bi₄-ma TÚG-pì-ri-kà-ni ša e-zi-bu na-pí-ší-šu-nu ù ṭup-pu-ú lu ša-ṣú-ru pì-ri-kà-nu ša ma-tí ù tí-bu-lá ma-a-<gap> iš-ta-ú-mu-ni a-dí en-um-a-šùr i-lá-kà-ni a ma-ma-an lá tù-šé-ri <gap> GÍN KÙ.BABBAR {d}UTU-tap-pá-i ub-lá-ki-im 1 GÍN KÙ.GI ù <gap> GÍN KÙ.BABBAR i-ku-pì-a ub-lá-ki-im → um-ma šu-ku-tum-ma a-na IŠTAR-lá-ma-sí ù ni-ta-aḫ-šu-šar qí-bi4-ma mì-šu ša ta-áš-pu-ra-ni-ni um-ma a-tí-na-ma É-tum a-na lá be-tim i-tù-ar a-pu-tum a-na en-um-a-šùr i-<gap>-ni-ma e ší-na ga <gap> ša lá ta-ḫa-dì-ri a-na IŠTAR-lá-ma-sí qí-bi4-ma šu-ma a-ḫa-tí a-ta li-ba-am dì-ni-ší-im lá ta-ḫa-da-ar a-na ni-ta-aḫ-šu-šar qí-bi4-ma TÚG-pì-ri-kà-ni ša e-zi-bu na-pí-ší-šu-nu ù ṭup-pu-ú lu ša-ṣú-ru pì-ri-kà-nu ša ma-tí ù tí-bu-lá ma-a-<gap> iš-ta-ú-mu-ni a-dí en-um-a-šùr i-lá-kà-ni a ma-ma-an lá tù-šé-ri <gap> GÍN KÙ.BABBAR {d}UTU-tap-pá-i ub-lá-ki-im 1 GÍN KÙ.GI ù <gap> GÍN KÙ.BABBAR i-ku-pì-a ub-lá-ki-im
 - um-ma šu-ta-mu-zi e-lá-a en-um-a-šùr ù lá-ma-sí-ma a-na en-um-a-šùr ù a-lá-ḫi-im qí-bi₄-ma a-ma-la na-áš-pé-er-tí-ku-nu ra-bi-ṣa-am ni-ḫu-za-ku-nu-tí a-bi-a DUMU be-e-be ra-bi₄-iṣ-ni i-na ša-am-ší ša ra-bi-ṣú-um e-ra-ba-ni iḫ-da-ma i-zi-za-ma lu DAM.GÀR a-bi-ku-nu lu ša a-wa-tám tí-šu-a-ni ra-bi-ṣú-um i-na ša-ḫa-tí-ku-nu li-zi-iz-ma i-na KÙ.BABBAR pá-ni-ma a-šar ta-ma-ḫa-ra-ni KÙ.BABBAR ša É a-lim{ki} šu-ta-aṣ-bi-ta-ma ma-lá a-bu-ku-nu ḫa-bu-lu KÙ.BABBAR ku-un-kà-ma šé-bi-lá-nim ra-bi₄-ṣú-um iš-tí-ku-nu li-ik-nu-uk-ma KÙ.BABBAR šé-bi-lá-nim-ma li-ma-am lu nu-ša-bi ṣí-ba-at ṣí-ib-tim lá i-ma-i-da-ku-nu-tí-ma li-ba-ku-nu e im-ra-aṣ ma-lá e-ṭá-ar É a-bi₄-ku-nu ep-ša šu-ma ta-da-ga-lá-ma ṭup-pu ḫa-ru-mu-tum ú ba-ba-a-tum ru-qá-tum i-ba-ší-ú ṭup-pí ku-un-kà-ma a-na DUMU um-me-a-nim ke-nim ša ki-ma ku-nu-tí pí-iq-da-ma u₄-me-e-ku-nu ba-lu-um mì-ma-ma lá tù-ri-qá-ma lá ta-sà-ḫu-ra iš-tí ra → um-ma šu-ta-mu-zi e-lá-a en-um-a-šùr ù lá-ma-sí-ma a-na en-um-a-šùr ù a-lá-ḫi-im qí-bi4-ma a-ma-la na-áš-pé-er-tí-ku-nu ra-bi-ṣa-am ni-ḫu-za-ku-nu-tí a-bi-a DUMU be-e-be ra-bi4-iṣ-ni i-na ša-am-ší ša ra-bi-ṣú-um e-ra-ba-ni iḫ-da-ma i-zi-za-ma lu DAM.GÀR a-bi-ku-nu lu ša a-wa-tám tí-šu-a-ni ra-bi-ṣú-um i-na ša-ḫa-tí-ku-nu li-zi-iz-ma i-na KÙ.BABBAR pá-ni-ma a-šar ta-ma-ḫa-ra-ni KÙ.BABBAR ša É a-lim{ki} šu-ta-aṣ-bi-ta-ma ma-lá a-bu-ku-nu ḫa-bu-lu KÙ.BABBAR ku-un-kà-ma šé-bi-lá-nim ra-bi4-ṣú-um iš-tí-ku-nu li-ik-nu-uk-ma KÙ.BABBAR šé-bi-lá-nim-ma li-ma-am lu nu-ša-bi ṣí-ba-at ṣí-ib-tim lá i-ma-i-da-ku-nu-tí-ma li-ba-ku-nu e im-ra-aṣ ma-lá e-ṭá-ar É a-bi4-ku-nu ep-ša šu-ma ta-da-ga-lá-ma ṭup-pu ḫa-ru-mu-tum ú ba-ba-a-tum ru-qá-tum i-ba-ší-ú ṭup-pí ku-un-kà-ma a-na DUMU um-me-a-nim ke-nim ša ki-ma ku-nu-tí pí-iq-da-ma u4-me-e-ku-nu ba-lu-um mì-ma-ma lá tù-ri-qá-ma lá ta-sà-ḫu-ra iš-tí ra
 - KIŠIB a-lá-ḫi-im KIŠIB a-li-li KIŠIB a-bi₄-lá KIŠIB lá-qé-ep ša i-na ba-áb-tim ša a-šùr-be-el-ma-al-ki-im ša iš-ti DUMU a-tù-ri-a ù a-mur-a-šùr ḫi-na-a iṣ-bu-tù-ma a-na e-lá-ma ip-qí-du 2 ma-na 13.5 GÍN KÙ.BABBAR ṣa-ru-pá-am e-lá-ma a-na a-lá-ḫi-im ù a-li-li ip-qí-du KÙ.BABBAR a-na a-lá-ḫi-im a-li-li ù ḫi-na-a a ba-re-šu-nu i-lá-ak → KIŠIB a-lá-ḫi-im KIŠIB a-li-li KIŠIB a-bi4-lá KIŠIB lá-qé-ep ša i-na ba-áb-tim ša a-šùr-be-el-ma-al-ki-im ša iš-ti DUMU a-tù-ri-a ù a-mur-a-šùr ḫi-na-a iṣ-bu-tù-ma a-na e-lá-ma ip-qí-du 2 ma-na 13.5 GÍN KÙ.BABBAR ṣa-ru-pá-am e-lá-ma a-na a-lá-ḫi-im ù a-li-li ip-qí-du KÙ.BABBAR a-na a-lá-ḫi-im a-li-li ù ḫi-na-a a ba-re-šu-nu i-lá-ak
Examples of Competition translation normalizations (original → normalized):
 - <gap> I entrusted to Šalim-wardī and Šu-Nūnu. Witnessed by Aššur-idī son of Mu-mulānum, by Aššur-taklāku son of Ikūnum son of Samaya.  → <gap> I entrusted to Šalim-wardī and Šu-Nūnu. Witnessed by Aššur-idī son of Mu-mulānum, by Aššur-taklāku son of Ikūnum son of Samaya.
 - Ennam-Aššur son of Suen-nādā has received 13 minas of refined silver, and Suen-nādā his son has received 5.3333 minas of refined silver . Witnessed by Aššur-imittī, by Išme-ilum, by Bi<gap> son of hannāniya, by Ilī-rē'ī son of Šakṣum.  → Ennam-Aššur son of Suen-nādā has received 13 minas of refined silver, and Suen-nādā his son has received 5.3333 minas of refined silver . Witnessed by Aššur-imittī, by Išme-ilum, by Bi<gap> son of hannāniya, by Ilī-rē'ī son of Šakṣum.
 - From Aššur-šadū'e, Amur-šarrassa and Šalim-wardī to Ali-ahum: Šalim-wardī brought 31 minas of tin under your seal. In accordance with your instructions we gave the tin to Amur-šarrassa and Šalim-wardī and they led it into the heartland, and they brought you (silver) at 6.5 shekels per (shekel) for your tin for you. Thereof we deposited 3.5 shekels as transport tariff. Šalim-wardī brings you 4.6666 minas 2.5 shekels of silver under our seals. We gave 1 shekel of silver for his disposal. With respect to Šu-Illil about whom we wrote to you, Šu-Illil son of Mannum-kī-Aššur promised 3 minas of silver to us. After Šalim-wardī came Šu-Illil was gone. Because of him we made Šalim-wardī wait 10 or 20 days. When Šu-Illil arrives we shall send a final report to you.  → From Aššur-šadū'e, Amur-šarrassa and Šalim-wardī to Ali-ahum: Šalim-wardī brought 31 minas of tin under your seal. In accordance with your instructions we gave the tin to Amur-šarrassa and Šalim-wardī and they led it into the heartland, and they brought you (silver) at 6.5 shekels per (shekel) for your tin for you. Thereof we deposited 3.5 shekels as transport tariff. Šalim-wardī brings you 4.6666 minas 2.5 shekels of silver under our seals. We gave 1 shekel of silver for his disposal. With respect to Šu-Illil about whom we wrote to you, Šu-Illil son of Mannum-kī-Aššur promised 3 minas of silver to us. After Šalim-wardī came Šu-Illil was gone. Because of him we made Šalim-wardī wait 10 or 20 days. When Šu-Illil arrives we shall send a final report to you.
 - To Ennam-Aššur from Šāt-Anna: As to the 2 minas 12.5 shekels of silver that I gave you, my dear brother, my dear lord, carry out the purchase yourself and send it with the very first transport. <gap> which I promised you, have him sell the textiles and the tin and send (the silver).  → To Ennam-Aššur from Šāt-Anna: As to the 2 minas 12.5 shekels of silver that I gave you, my dear brother, my dear lord, carry out the purchase yourself and send it with the very first transport. <gap> which I promised you, have him sell the textiles and the tin and send (the silver).
 - <gap> Save me while I can still be saved. Of the 11 minas of silver from your tablet, 5 minas of silver <gap> the two minas of silver that you promised to pay during the journey and which you have not paid - send the silver. I shall buy good and lapis lazuli for you, and you will see that we shall take 10 minas of silver <gap> when I come up <gap> Sell the tin and textiles for silver. Pay attention to my outstanding claims with Anatolians, have the silver paid and send it to me. I have seen good iron and good lapis lazuli here in the City Hall, but as long as they have not paid the silver, they will not release the iron and lapis lazuli. My dear brother, take care to convert the tin and textiles to silver and then have some 10 minas of silver from my outstanding claims paid, and send me the silver so I can take out the iron and the lapis lazuli, and since in the palace gate <gap> they should come here. <gap> of others <gap>  → <gap> Save me while I can still be saved. Of the 11 minas of silver from your tablet, 5 minas of silver <gap> the two minas of silver that you promised to pay during the journey and which you have not paid - send the silver. I shall buy good and lapis lazuli for you, and you will see that we shall take 10 minas of silver <gap> when I come up <gap> Sell the tin and textiles for silver. Pay attention to my outstanding claims with Anatolians, have the silver paid and send it to me. I have seen good iron and good lapis lazuli here in the City Hall, but as long as they have not paid the silver, they will not release the iron and lapis lazuli. My dear brother, take care to convert the tin and textiles to silver and then have some 10 minas of silver from my outstanding claims paid, and send me the silver so I can take out the iron and the lapis lazuli, and since in the palace gate <gap> they should come here. <gap> of others <gap>
 - 4 silver beads, the debt of <gap>, remains.  → 4 silver beads, the debt of <gap>, remains.
Examples of Akkademia transliteration normalizations (original → normalized):
 - 𒉆𒁍𒌝𒋾𒂗𒌑𒉀𒂵𒆠𒉈𒋙𒄇𒃻𒀭𒂗𒈨𒊹𒊏𒆥𒈠𒉌𒆥𒈠𒉌𒅗DE₂𒈨𒌍 → 𒉆𒁍𒌝𒋾𒂗𒌑𒉀𒂵𒆠𒉈𒋙𒄇𒃻𒀭𒂗𒈨𒊹𒊏𒆥𒈠𒉌𒆥𒈠𒉌𒅗DE2𒈨𒌍
 - 𒌓𒌋𒌋𒐌𒆚n(ban₂)𒌓𒌋𒌋𒐍𒆚𒑐𒌓𒌋𒌋𒑆𒆚 → 𒌓𒌋𒌋𒐌𒆚n(ban2)𒌓𒌋𒌋𒐍𒆚𒑐𒌓𒌋𒌋𒑆𒆚
 - n(ban₂)𒐈𒋡𒌓𒌋𒌋𒐈𒆚 → n(ban2)𒐈𒋡𒌓𒌋𒌋𒐈𒆚
 - n(ban₂)𒐉𒋡𒌓𒌋𒌋𒐉𒆚 → n(ban2)𒐉𒋡𒌓𒌋𒌋𒐉𒆚
 - n(ban₂)...𒋡𒌓𒌋𒌋𒐋𒆚 → n(ban2)...𒋡𒌓𒌋𒌋𒐋𒆚
 - 𒌋𒀲𒊺𒉻𒈨𒌍𒐊𒀲n(ban₂)𒊺𒈪𒉭𒈨𒌍𒀀𒈾 → 𒌋𒀲𒊺𒉻𒈨𒌍𒐊𒀲n(ban2)𒊺𒈪𒉭𒈨𒌍𒀀𒈾
Examples of Akkademia translation normalizations (original → normalized):
 - warrior ... who made ... bow down at his feet ... , who put ... to the sword (lit. “weapon”), ... circumspect ... , → warrior ... who made ... bow down at his feet ... , who put ... to the sword (lit. "weapon"), ... circumspect ... ,
 - I adorned them (statues of the gods) and they (the gods) went (back) to their land. I rebuilt those cities. I built a city on top of a tell (lit. “a heaped-up ruin mound”) called Ḫumut. I built (and) completed (it) from its foundations to its parapets. Inside (it), I founded a palace for my royal residence. I named it Kār-Aššur, set up the weapon of (the god) Aššur, my lord, therein, (and) settled the people of (foreign) lands conquered by me therein. I imposed upon them tax (and) tribute, (and) considered them as inhabitants of Assyria. → I adorned them (statues of the gods) and they (the gods) went (back) to their land. I rebuilt those cities. I built a city on top of a tell (lit. "a heaped-up ruin mound") called Ḫumut. I built (and) completed (it) from its foundations to its parapets. Inside (it), I founded a palace for my royal residence. I named it Kār-Aššur, set up the weapon of (the god) Aššur, my lord, therein, (and) settled the people of (foreign) lands conquered by me therein. I imposed upon them tax (and) tribute, (and) considered them as inhabitants of Assyria.
 - I fashioned (on a stele) my royal image and the image(s) of the great gods, my lords, inscribed on it the mighty victories (lit. “victory and might”) (5) that I had achieved again and again over (foreign) lands in the name of (the god) Aššur, my lord, (and) I erected (it) in ... → I fashioned (on a stele) my royal image and the image(s) of the great gods, my lords, inscribed on it the mighty victories (lit. "victory and might") (5) that I had achieved again and again over (foreign) lands in the name of (the god) Aššur, my lord, (and) I erected (it) in ...
 - Bātānu of (the land Bīt)-Kapsi (lit. “son of Kapsi”) → Bātānu of (the land Bīt)-Kapsi (lit. "son of Kapsi"
 - , submitted, and became (my) vassal (lit. “took up corvée labor”) so that his district would not be dispersed. (Thus) I left him the city Karkariḫundir → , submitted, and became (my) vassal (lit. "took up corvée labor") so that his district would not be dispersed. (Thus) I left him the city Karkariḫundir
 - (and) I plundered (it). Ramateia of the land Araziaš ... He fled furtively (lit. “like a centipede”) and no one found his (hiding) place... I offered ... , horses, oxen, sheep and goats, lapis lazuli hewn from its mountain, ... to the great gods, my lords. → and) I plundered (it). Ramateia of the land Araziaš ... He fled furtively (lit. "like a centipede") and no one found his (hiding) place... I offered ... , horses, oxen, sheep and goats, lapis lazuli hewn from its mountain, ... to the great gods, my lords.
Examples of ORACC transliteration normalizations (original → normalized):
 - [ x x ] ⸢ x ⸣ É ⸢ x ⸣ + [ x x x x x x x x ] [ a ] - ⸢ du ⸣ - ú LÚ . e - mu - qí - ⸢ ia it ⸣ - [ tal - ku - ni ] ⸢ ip ⸣ - paḫ - ru ù i - na pa - an [ x x x šu - nu ] [ la ? ] ITI ù UD - mu šá i - na ŠÀ - bi [ i - kaš - šá - du ] [ a ] — ⸢ ki ⸣ - ma a - na pa - ni - ka il - ⸢ la ⸣ - [ ku - ni x x ] [ ḫu ] - ⸢ us ⸣ - sa - am - ma šup - ra ina [ x x x x ] (erased x x x x x x x x) [ ki - ma e ] - ⸢ mu ⸣ - qí - ia it - tal - ku - ni [ x x x x ] [ la ] ⸢ i * ⸣ - di - nu - nik ù ma - la ⸢ x ⸣ + [ x x x x ] [ x ] ⸢ x ⸣ kit - ta ki - i pi - i šá ⸢ x ⸣ + [ x x x x ] [ x x ] dib - bi - ka la il - lu - [ ú x x x ] [ a - na ] ṣa - ba - a - ti la ta - ⸢ nam ⸣ - [ din x x x ] [ it - ta ] - aṣ - ru ki - ṣir - ku - nu la [ x x x x ] [ a - di e ] - ⸢ mu ⸣ - qí - ia i - kaš - šá - du [ x x x x ] → <gap> ⸢ x ⸣ É ⸢ x ⸣ + <gap> <gap> - ⸢ du ⸣ - ú LÚ . e - mu - qí - ⸢ ia it ⸣ - <gap> ⸢ ip ⸣ - paḫ - ru ù i - na pa - an <gap> <gap> ITI ù UD - mu šá i - na ŠÀ - bi <gap> <gap> — ⸢ ki ⸣ - ma a - na pa - ni - ka il - ⸢ la ⸣ - <gap> <gap> - ⸢ us ⸣ - sa - am - ma šup - ra ina <gap> (erased x x x x x x x x) <gap> - ⸢ mu ⸣ - qí - ia it - tal - ku - ni <gap> <gap> ⸢ i * ⸣ - di - nu - nik ù ma - la ⸢ x ⸣ + <gap> <gap> ⸢ x ⸣ kit - ta ki - i pi - i šá ⸢ x ⸣ + <gap> <gap> dib - bi - ka la il - lu - <gap> <gap> ṣa - ba - a - ti la ta - ⸢ nam ⸣ - <gap> <gap> - aṣ - ru ki - ṣir - ku - nu la <gap> <gap> - ⸢ mu ⸣ - qí - ia i - kaš - šá - du <gap>
 - [ a - na LUGAL be - lí - ia ] ⸢ ARAD * ⸣ - [ ka m x x x x x x ] a - na ⸢ di * - na * - an * ⸣ [ LUGAL EN - ia lul - lik ] lu - ú šul - ⸢ mu ⸣ [ a - na LUGAL be - lí - ia ] um - ma - a a - na ⸢ LUGAL ⸣ [ be - lí - ia - a - ma ] ki - i áš - mu - ú [ x x x x x x ] um - ma - a m d AMAR . [ UTU — x x x x x ] um - ma - a LÚ . gam - bu - [ la - a . a x x x ] lid - di - nu ku - [ x x x x x x x ] LÚ . gam - bu - lu - a . [ a x x x x x ] a - na UGU - ḫi [ x x x x x x x ] LUGAL ŠEŠ - ka šá [ x x x x x x x ] mim - mu - ú a - na [ x x x x x ] la ṭa - bu [ x x x x x x x ] ul i - ter - [ bu x x x x x x ] ul i - qab - ⸢ bi ⸣ [ x x x x ] ki pi an - [ ni - i x x x x x x ] a - na ŠEŠ - ía [ x x x x x ] um - ma - a ⸢ LUGAL ⸣ [ x x x x ] ki - i i - mur [ x x x x x ] i - dab - bu - ⸢ ub ⸣ [ x x x x ] a - na - ku ina ⸢ UGU ⸣ [ x x x x ] šá - ni - ti [ x x x x x ] ki - i [ x x x x x x x x x ] šá LUGAL ⸢ be ⸣ - [ lí - ia x x x x x ] a - mat e - [ x x x x x x x x ] i - na pa - [ an x x x x x x x ] a - di tak - [ x x x x x x x x ] a - qab - bi [ x x x x x x x x ] i - na bi - [ x x x x x x x x ] a - mat a - qab - ⸢ bi ⸣ [ x x x x x x x ] ti - da - a [ x x x x x x x x ] a - di er - ⸢ bet ⸣ [ x x x x x x x ] ⸢ ki ⸣ - i áš - mu - [ ú x x x x x x ] [ a ] - ⸢ na ⸣ LUGAL i - ⸢ qab ⸣ - [ bi x x x x x ] [ m d U ] . GUR — ŠEŠ - ir [ x x x x x x ] [ ki ] - i iq - bu - [ ú x x x x x ] [ x ] ⸢ iq * ⸣ - ba - aʾ * [ x x x x x x ] [ it ] - ta - lak [ x x x x x x x ] [ x x ] tak KUR [ x x x x x x x ] [( x ) x ] i si * [ x x x x x x x ] [ at ] - ta - ma [ x x x x x x x ] ⸢ ak ⸣ - ka - a . a - i [ x x x x x x ] lu - kul LÚ . pu - [ qu - du x x x x x ] šá LUGAL ù ⸢ ŠEŠ ⸣ - [ šú x x x ] i - na ŠU .2 [ x x x x x x ] šá KUR . ra - a - ⸢ ši ⸣ [ x x x x x x ] ki - i ak - [ x x x x x x x ] [ x ] ⸢ x ⸣ - ʾa - [ x x x x x x x ] [ x x x x ] ḫal [ x x x x x x x ] LUGAL li - is - ni - qa - an - ni [ šá ] LÚ . qí - i - pi šá KUR . ra - ⸢ a ⸣ - šú ik - kal a - na - ku - ma lu - kul šá LUGAL mi - nu - ú [ 0 ] muṭ - ṭè - e - šú → <gap> ⸢ ARAD * ⸣ - <gap> a - na ⸢ di * - na * - an * ⸣ <gap> lu - ú šul - ⸢ mu ⸣ <gap> um - ma - a a - na ⸢ LUGAL ⸣ <gap> ki - i áš - mu - ú <gap> um - ma - a m d AMAR . <gap> um - ma - a LÚ . gam - bu - <gap> lid - di - nu ku - <gap> LÚ . gam - bu - lu - a . <gap> a - na UGU - ḫi <gap> LUGAL ŠEŠ - ka šá <gap> mim - mu - ú a - na <gap> la ṭa - bu <gap> ul i - ter - <gap> ul i - qab - ⸢ bi ⸣ <gap> ki pi an - <gap> a - na ŠEŠ - ía <gap> um - ma - a ⸢ LUGAL ⸣ <gap> ki - i i - mur <gap> i - dab - bu - ⸢ ub ⸣ <gap> a - na - ku ina ⸢ UGU ⸣ <gap> šá - ni - ti <gap> ki - i <gap> šá LUGAL ⸢ be ⸣ - <gap> a - mat e - <gap> i - na pa - <gap> a - di tak - <gap> a - qab - bi <gap> i - na bi - <gap> a - mat a - qab - ⸢ bi ⸣ <gap> ti - da - a <gap> a - di er - ⸢ bet ⸣ <gap> ⸢ ki ⸣ - i áš - mu - <gap> <gap> - ⸢ na ⸣ LUGAL i - ⸢ qab ⸣ - <gap> <gap> . GUR — ŠEŠ - ir <gap> <gap> - i iq - bu - <gap> <gap> ⸢ iq * ⸣ - ba - aʾ * <gap> <gap> - ta - lak <gap> <gap> tak KUR <gap> <gap> i si * <gap> <gap> - ta - ma <gap> ⸢ ak ⸣ - ka - a . a - i <gap> lu - kul LÚ . pu - <gap> šá LUGAL ù ⸢ ŠEŠ ⸣ - <gap> i - na ŠU .2 <gap> šá KUR . ra - a - ⸢ ši ⸣ <gap> ki - i ak - <gap> <gap> ⸢ x ⸣ - ʾa - <gap> <gap> ḫal <gap> LUGAL li - is - ni - qa - an - ni <gap> LÚ . qí - i - pi šá KUR . ra - ⸢ a ⸣ - šú ik - kal a - na - ku - ma lu - kul šá LUGAL mi - nu - ú <gap> muṭ - ṭè - e - šú
 - [ x x x x x x x ] ⸢ x ⸣ [ x x x x x x x x ] - pi [ x x ] ⸢ x x ⸣ ki - i ⸢ x ⸣ [ x ] [ ŠU .2 ? ] m za - ki - ri DUMU i - [ ba - a ] [ iš ] - pu - ra um - ma LUGAL [ 0 ] [ KI ] LÚ . NAM - MEŠ um - ma [ 0 ] [ ina IGI ] - ka lil - li - ⸢ ka ⸣ [ at ] - ⸢ ta ⸣ taš - pu - ra [ 0 ] [ um ] - ⸢ ma ⸣ al - ka at - ta [ ul ] ⸢ ti ⸣ - de - e ki - i [ Á ? ] ⸢ la ⸣ ba - ni - ti ù [ šá a ] - ⸢ na ⸣ du - un - qí [ x x ] ⸢ x x x x x x ⸣ → <gap> ⸢ x ⸣ <gap> - pi <gap> ⸢ x x ⸣ ki - i ⸢ x ⸣ <gap> <gap> m za - ki - ri DUMU i - <gap> <gap> - pu - ra um - ma LUGAL <gap> <gap> LÚ . NAM - MEŠ um - ma <gap> <gap> - ka lil - li - ⸢ ka ⸣ <gap> - ⸢ ta ⸣ taš - pu - ra <gap> <gap> - ⸢ ma ⸣ al - ka at - ta <gap> ⸢ ti ⸣ - de - e ki - i <gap> ⸢ la ⸣ ba - ni - ti ù <gap> - ⸢ na ⸣ du - un - qí <gap> ⸢ x x x x x x ⸣

## 8. Preprocessing Summary

In [ ]:
print('=' * 80)
print('FINAL PREPROCESSING SUMMARY')
print('=' * 80)

# Create comprehensive before/after comparison
summary_data = []

# Competition datasets (not modified)
summary_data.append(['Competition', 'train', len(train_df), len(train_df), 0, 'Source dataset (preserved)'])
summary_data.append(['Competition', 'test', len(test_df), len(test_df), 0, 'Held-out test set'])

# Akkademia datasets
summary_data.append(['Akkademia', 'train', len(akkademia_data['train']), len(akkademia_deduped['train']), 
                     len(akkademia_data['train']) - len(akkademia_deduped['train']), 'Overlap/duplicates removed'])
summary_data.append(['Akkademia', 'valid', len(akkademia_data['valid']), len(akkademia_deduped['valid']), 
                     len(akkademia_data['valid']) - len(akkademia_deduped['valid']), 'Overlap/duplicates removed'])
summary_data.append(['Akkademia', 'test', len(akkademia_data['test']), len(akkademia_deduped['test']), 
                     len(akkademia_data['test']) - len(akkademia_deduped['test']), 'Overlap/duplicates removed'])

# ORACC dataset
summary_data.append(['ORACC', 'train', len(oracc_df), len(oracc_deduped), 
                     len(oracc_df) - len(oracc_deduped), 'Overlap/duplicates removed'])

# Sentences_Oare
summary_data.append(['Sentences_Oare', 'all', len(sentences_oare_df), len(sentences_oare_filtered), 
                     len(sentences_oare_df) - len(sentences_oare_filtered), 'Nulls/overlap removed'])

summary_comparison = pd.DataFrame(summary_data, columns=[
    'Dataset', 'Split', 'Before', 'After', 'Removed', 'Note'
])
summary_comparison.index = range(1, len(summary_comparison) + 1)

print('\nDataset Processing Summary:')
display(summary_comparison)

# Stage dataset summary
print('\n' + '-' * 80)
print('Training Stage Datasets:')
print('-' * 80)

stage_summary = pd.DataFrame({
    'Stage': ['Stage 1', 'Stage 2', 'Stage 3', 'Stage 3'],
    'Purpose': [
        'General Akkadian (external data)',
        'Domain adaptation (OARE sentences)',
        'Fine-tuning (competition train)',
        'Validation split'
    ],
    'Split': ['train', 'train', 'train', 'val'],
    'Rows': [len(stage1_data), len(stage2_data), len(stage3_train), len(stage3_val)],
    'Source': [
        'Akkademia train+valid, ORACC',
        'Sentences_Oare (filtered)',
        'Competition train (90%)',
        'Competition train (10%)'
    ]
})
stage_summary.index = range(1, len(stage_summary) + 1)
display(stage_summary)

print(f'\n📖 Glossary entries (proper names): {len(glossary_dict)}')
print(f'\n💾 All preprocessed datasets saved to data/ directory')
print(f'✅ Preprocessing pipeline complete!')

                           count
Competition train rows      1561
Competition test rows          4
Akkademia train (deduped)  44511
Akkademia valid (deduped)   2712
Akkademia test  (deduped)   2762
ORACC (deduped)             2111
Sentences_Oare (filtered)   8565
Stage 1 train rows         49334
Stage 2 train rows          8565
Stage 3 train rows          1404
Stage 3 val rows             157
Glossary entries           13438